import React, { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { resolveProfileImportFormat } from '../../../../src/utils/profileImportFormat';
const typeNames = { KIT_LADDER: 'Аллельные лестницы', NIST_VARIANTS: 'Известные STR-варианты', Y_STR_REFERENCE: 'Y-хромосомные справочники', OBSERVED_REFERENCE: 'Подтверждённые локальные записи' };
const empty = () => ({ name: '', type: 'KIT_LADDER', manufacturer: '', kitName: '', kitVersion: '', sourceTitle: '', sourceUrl: '', sourceVersion: '', sourceDate: '', format: 'json', content: '', confirmed: false });
const fields = [['name', 'Название справочника', 150], ['manufacturer', 'Производитель', 150], ['kitName', 'Генотипирующий набор', 150], ['kitVersion', 'Версия набора', 150], ['sourceTitle', 'Название документа / источника', 300], ['sourceUrl', 'Ссылка на источник', 2000], ['sourceVersion', 'Версия документа / источника', 150]];
export default function AlleleReferencesPage() {
  const { user, activeDepartment, activeDepartmentId } = useAuth();
  const allowed = resolveProfileImportFormat(activeDepartment) === 'genetic';
  const canEdit = ['system_administrator', 'admin', 'department_head'].includes(user?.role);
  const [references, setReferences] = useState([]), [panels, setPanels] = useState([]);
  const [draft, setDraft] = useState(null), [validation, setValidation] = useState(null);
  const [selected, setSelected] = useState(null), [locus, setLocus] = useState(''), [page, setPage] = useState(0);
  const [type, setType] = useState(''), [compareId, setCompareId] = useState(''), [comparison, setComparison] = useState(null);
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const request = async (path, options = {}, base = '/api/allele-references') => {
    const response = await fetch(base + path, { ...options, headers: { Authorization: `Bearer ${user?.accessToken || localStorage.getItem('token')}`, 'X-Active-Department-Id': activeDepartmentId, 'Content-Type': 'application/json' } });
    const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Ошибка справочников.'); return result;
  };
  const load = async signal => {
    const [refs, panels] = await Promise.all([request('?includeInactive=true', { signal }), request('?includeInactive=true', { signal }, '/api/genotype-panels')]);
    if (!signal?.aborted) { setReferences(refs.references); setPanels(panels.panels); }
  };
  useEffect(() => {
    const controller = new AbortController(); setReferences([]); setPanels([]); setDraft(null); setSelected(null); setComparison(null); setValidation(null); setError(''); setMessage('');
    if (allowed) { setBusy(true); load(controller.signal).catch(error => { if (!controller.signal.aborted) setError(error.message); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); }
    return () => controller.abort();
  }, [activeDepartmentId, allowed]);
  const perform = async operation => { setBusy(true); setError(''); setMessage(''); try { await operation(); } catch (error) { setError(error.message); } finally { setBusy(false); } };
  const edit = patch => { setDraft(previous => ({ ...previous, ...patch })); setValidation(null); };
  const select = reference => perform(async () => { setSelected(await request(`/${reference.id}`)); setLocus(''); setPage(0); setCompareId(''); setComparison(null); });
  const link = (panel, checked) => perform(async () => {
    const ids = checked ? [...panel.referenceSetIds, selected.id] : panel.referenceSetIds.filter(id => id !== selected.id);
    const result = await request(`/${panel.id}`, { method: 'PUT', body: JSON.stringify({ ...panel, referenceSetIds: ids }) }, '/api/genotype-panels');
    setPanels(previous => previous.map(item => item.id === panel.id ? result.panel : item)); setMessage('Связь панели сохранена. Выбор лестницы основан на этой связи.');
  });
  const values = selected?.values.filter(value => !locus || value.locus === locus) || [];
  const current = Math.min(page, Math.max(0, Math.ceil(values.length / 100) - 1));
  return <div className="references-page"><header className="page-header"><div><h1>Генетические справочники</h1><p>Версии аллельных лестниц, известных вариантов и источники подтверждённых данных.</p></div>{allowed && canEdit && <button className="btn btn-primary" disabled={busy} onClick={() => { setDraft(empty()); setValidation(null); }}>Добавить справочник</button>}</header>
    {!allowed ? <div className="alert alert-info">Выберите отделение «Генетические экспертизы».</div> : <>
      {error && <div className="alert alert-danger" role="alert">{error}</div>}{message && <div className="alert alert-success" role="status">{message}</div>}
      <section className="card references-card"><h2>Источники данных</h2><p>Импортируйте проверенные точные перечни из документации вашего набора. Частотные базы управляются в существующем меню «Популяции». Данные для конвертации обрабатываются локально.</p><ul>
        <li><a href="https://strbase.nist.gov/" target="_blank" rel="noopener noreferrer">NIST STRBase</a> — известные варианты; отсутствие записи не доказывает невозможность аллели.</li>
        <li><a href="https://www.thermofisher.com/us/en/home/industrial/forensics/human-identification/forensic-dna-analysis/pcr-amplification-forensic-dna-profiling/globalfiler.html" target="_blank" rel="noopener noreferrer">Thermo Fisher</a> — документация GlobalFiler, IQC и других наборов; версии выбираются явно.</li>
        <li><a href="https://www.promega.com/resources/protocols/" target="_blank" rel="noopener noreferrer">Promega</a> — официальная документация PowerPlex.</li>
        <li><a href="https://yhrd.org/" target="_blank" rel="noopener noreferrer">YHRD</a> — информация о Y-гаплотипах; частоты независимых аутосомных локусов не применяются.</li>
      </ul>{canEdit && <><p>Подготовлен точный перечень PowerPlex Fusion из TMD039, редакция 7/20, таблица 7. Перед сохранением проверьте соответствие используемому набору и версии документа.</p><button className="btn btn-secondary" disabled={busy} onClick={() => perform(async () => { const template = await request('/templates/promega-fusion-tmd039-2020'); setDraft({ ...empty(), ...template, format: 'json', content: JSON.stringify({ kit: template.kitName, loci: template.loci }, null, 2), confirmed: false }); setValidation(null); })}>Подготовить PowerPlex Fusion TMD039 7/20</button></>}</section>
      <label className="form-label">Тип справочника<select className="form-input" value={type} onChange={event => setType(event.target.value)}><option value="">Все источники</option>{Object.entries(typeNames).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>
      <div className="table-container"><table className="table"><thead><tr><th>Название / версия</th><th>Тип</th><th>Набор</th><th>Локусы / аллели</th><th>Источник</th><th>Действия</th></tr></thead><tbody>{references.filter(reference => !type || reference.type === type).map(reference => <tr key={reference.id}><td>{reference.name}<br />{reference.sourceVersion}{!reference.isActive && <p>Деактивирован</p>}</td><td>{typeNames[reference.type]}</td><td>{reference.kitName || '—'}</td><td>{reference.loci.length} / {reference.valueCount}</td><td><a href={reference.sourceUrl} target="_blank" rel="noopener noreferrer">{reference.sourceTitle}</a><br />{reference.sourceDate ? new Date(reference.sourceDate).toLocaleDateString('ru-RU') : 'Дата не указана'}</td><td><button className="btn btn-secondary" disabled={busy} onClick={() => select(reference)}>Просмотреть</button>{canEdit && <button className="btn btn-secondary" disabled={busy} onClick={() => perform(async () => { await request(`/${reference.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !reference.isActive }) }); await load(); if (selected?.id === reference.id) setSelected(previous => ({ ...previous, isActive: !reference.isActive })); })}>{reference.isActive ? 'Деактивировать' : 'Активировать'}</button>}</td></tr>)}{!references.length && <tr><td colSpan="6">Справочники не загружены. Добавьте проверенный CSV/JSON с указанием источника.</td></tr>}</tbody></table></div>
      {draft && <section className="card references-card"><h2>{draft.previousSetId ? 'Новая версия справочника' : 'Импорт справочника'}</h2><form onSubmit={event => { event.preventDefault(); perform(async () => { const result = await request('/validate', { method: 'POST', body: JSON.stringify(draft) }); setValidation(result); }); }}>
        <div className="references-fields"><label>Тип<select className="form-input" value={draft.type} disabled={busy || !!draft.previousSetId} onChange={event => edit({ type: event.target.value })}>{Object.entries(typeNames).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>{fields.map(([key, title, limit]) => <label key={key}>{title}<input className="form-input" type={key === 'sourceUrl' ? 'url' : 'text'} required={['name', 'sourceTitle', 'sourceUrl', 'sourceVersion'].includes(key) || key === 'kitName' && draft.type === 'KIT_LADDER'} disabled={busy || key === 'name' && !!draft.previousSetId} maxLength={limit} value={draft[key] || ''} onChange={event => edit({ [key]: event.target.value })} /></label>)}<label>Дата документа<input className="form-input" type="date" value={draft.sourceDate || ''} disabled={busy} onChange={event => edit({ sourceDate: event.target.value })} /></label></div>
        <div className="references-actions"><label>Формат<select className="form-input" value={draft.format} disabled={busy} onChange={event => edit({ format: event.target.value })}><option value="json">JSON</option><option value="csv">CSV</option></select></label><label>Файл CSV/JSON<input type="file" accept=".csv,.json" disabled={busy} onChange={event => { const file = event.target.files[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) { setError('Файл превышает 8 МиБ.'); return; } perform(async () => edit({ format: file.name.toLowerCase().endsWith('.csv') ? 'csv' : 'json', content: await file.text() })); }} /></label></div>
        <label>Содержимое<textarea className="form-input references-content" value={draft.content} disabled={busy} onChange={event => edit({ content: event.target.value })} placeholder={draft.format === 'csv' ? 'Kit,Locus,Allele,Classification' : 'Объект с полем loci или массив записей locus / allele'} required /></label>
        <p>Каждая аллель — строка. Указывайте точный состав опубликованной лестницы; не заполняйте диапазоны по минимальному и максимальному значениям.</p><label className="references-confirm"><input type="checkbox" checked={draft.confirmed} disabled={busy} onChange={event => edit({ confirmed: event.target.checked })} required />Значения сверены с указанным источником; условия использования данных соблюдены.</label>
        <div className="references-actions"><button className="btn btn-secondary" disabled={busy} type="submit">Проверить данные</button><button className="btn btn-primary" disabled={busy || !validation} type="button" onClick={() => perform(async () => { await request('', { method: 'POST', body: JSON.stringify(draft) }); setDraft(null); setValidation(null); await load(); setMessage('Версия справочника импортирована. Свяжите её с нужной панелью.'); })}>Сохранить проверенную версию</button><button className="btn btn-secondary" type="button" disabled={busy} onClick={() => setDraft(null)}>Отмена</button></div>
        {validation && <div role="status"><p>Проверка пройдена: {validation.valueCount} записей · локусы: {validation.loci.join(', ')}</p><pre className="references-preview">{JSON.stringify(validation.preview, null, 2)}</pre></div>}
      </form></section>}
      {selected && <section className="card references-card"><h2>{selected.name} · {selected.sourceVersion}</h2><p>{selected.sourceTitle} · SHA-256: <span className="references-hash">{selected.contentHash}</span></p><div className="references-actions"><label>Локус<select className="form-input" value={locus} onChange={event => { setLocus(event.target.value); setPage(0); }}><option value="">Все локусы</option>{[...new Set(selected.values.map(value => value.locus))].map(name => <option key={name}>{name}</option>)}</select></label>{canEdit && <button className="btn btn-secondary" disabled={busy} onClick={() => { setDraft({ ...empty(), ...selected, sourceDate: selected.sourceDate ? new Date(selected.sourceDate).toISOString().slice(0, 10) : '', sourceVersion: '', previousSetId: selected.id, content: JSON.stringify({ values: selected.values }, null, 2), confirmed: false }); setValidation(null); }}>Создать новую версию</button>}</div>
        <div className="table-container"><table className="table"><thead><tr><th>Локус</th><th>Аллель</th><th>Классификация</th></tr></thead><tbody>{values.slice(current * 100, current * 100 + 100).map(value => <tr key={`${value.locus}:${value.allele}`}><td>{value.locus}</td><td>{value.allele}</td><td>{value.classification}</td></tr>)}</tbody></table></div><div className="references-actions"><button className="btn btn-secondary" disabled={!current} onClick={() => setPage(current - 1)}>Назад</button><span>{current + 1} / {Math.max(1, Math.ceil(values.length / 100))}</span><button className="btn btn-secondary" disabled={(current + 1) * 100 >= values.length} onClick={() => setPage(current + 1)}>Далее</button></div>
        <h3>Подтверждённая связь с панелями</h3><p>Название панели само по себе не назначает лестницу. При нескольких активных версиях оператор выбирает версию в конвертере.</p><div className="references-links">{panels.map(panel => <label key={panel.id}><input type="checkbox" disabled={busy || !canEdit} checked={panel.referenceSetIds.includes(selected.id)} onChange={event => link(panel, event.target.checked)} />{panel.name}{!panel.isActive && ' (неактивная)'}</label>)}</div>
        <h3>Сравнение версий</h3><div className="references-actions"><select className="form-input" aria-label="Версия для сравнения" value={compareId} onChange={event => { setCompareId(event.target.value); setComparison(null); }}><option value="">Выберите версию</option>{references.filter(reference => reference.id !== selected.id).map(reference => <option key={reference.id} value={reference.id}>{reference.name} · {reference.sourceVersion}</option>)}</select><button className="btn btn-secondary" disabled={busy || !compareId} onClick={() => perform(async () => setComparison(await request(`/${selected.id}/compare?other=${compareId}`)))}>Сравнить</button></div>{comparison && <><p>Добавлено: {comparison.added.length} · Удалено: {comparison.removed.length} · Изменено: {comparison.changed.length}</p><pre className="references-preview">{JSON.stringify({ added: comparison.added.slice(0, 100), removed: comparison.removed.slice(0, 100), changed: comparison.changed.slice(0, 100) }, null, 2)}</pre></>}
      </section>}
    </>}
  </div>;
}
