import React from 'react';
export default function ConverterSources({ result, options, update, disabled }) {
  const set = (id, patch) => update({ ...options, files: { ...options.files, [id]: { ...options.files?.[id], ...patch } } });
  return <section className="converter-card"><h2>Источники и панели</h2>{result.files.map(file => <details key={file.id} open={result.files.length === 1 || file.objectColumn == null || file.columns.some(column => !column.locus && !column.ignored && column.index !== file.objectColumn)}>
    <summary>{file.name} · {file.rowCount} строк · {file.sourceLoci.length} локусов</summary>
    <div className="converter-source-controls">
      <label>Лист<select className="form-input" value={file.sheet || ''} disabled={disabled} onChange={event => set(file.id, { sheetName: event.target.value, headerRow: undefined, objectColumn: undefined, columns: {} })}><option value="" disabled>Выберите лист</option>{file.sheets.map(name => <option key={name}>{name}</option>)}</select></label>
      <label>Строка заголовков<select className="form-input" value={file.headerRow || ''} disabled={disabled} onChange={event => set(file.id, { headerRow: Number(event.target.value), objectColumn: undefined, columns: {} })}><option value="" disabled>Выберите строку</option>{file.sampleRows?.map(row => <option key={row.row} value={row.row}>{row.row}: {row.values.join(' | ')}</option>)}</select></label>
      <label>Полный номер объекта<select className="form-input" value={file.objectColumn ?? ''} disabled={disabled} onChange={event => set(file.id, { objectColumn: Number(event.target.value) })}><option value="" disabled>Выберите колонку</option>{file.columns.map(column => <option key={column.index} value={column.index}>{column.letter}: {column.header || '(без заголовка)'} {file.objectCandidates.find(candidate => candidate.index === column.index)?.examples.join(', ')}</option>)}</select></label>
      <label>Панель<select className="form-input" value={file.detectedPanelId || ''} disabled={disabled} onChange={event => set(file.id, { panelId: event.target.value })}><option value="">Не указана</option>{file.panelCandidates.map(panel => <option key={panel.id} value={panel.id}>{panel.name} — {panel.matches}/{panel.expected}, отсутствуют {panel.missing.length}, лишние {panel.extra.length}</option>)}</select></label>
      <label>Версия лестницы для файла<select className="form-input" value={options.files?.[file.id]?.referenceSetId || 'auto'} disabled={disabled} onChange={event => set(file.id, { referenceSetId: event.target.value })}><option value="auto">Автоматически по панели</option><option value="none">Не использовать</option>{result.referenceSets?.filter(set => set.type === 'KIT_LADDER').map(set => <option key={set.id} value={set.id}>{set.name} · {set.sourceVersion}</option>)}</select></label>
    </div>
    {file.columns.filter(column => column.index !== file.objectColumn && !column.ignored && !column.locus || options.files?.[file.id]?.columns?.[column.index]).map(column => <label className="converter-mapping" key={column.index}>{column.letter}: {column.header || '(без заголовка)'}{column.suggestions?.length > 0 && <span>Возможные: {column.suggestions.join(', ')}</span>}<select className="form-input" value={column.ignored ? '__ignore' : column.locus || ''} disabled={disabled} onChange={event => set(file.id, { columns: { ...options.files?.[file.id]?.columns, [column.index]: event.target.value === '__ignore' ? { ignore: true } : { locus: event.target.value } } })}><option value="">Сопоставьте или игнорируйте</option><option value="__ignore">Игнорировать</option>{result.catalogLoci.map(locus => <option key={locus}>{locus}</option>)}</select></label>)}
    <p>Локусы источника: {file.sourceLoci.join(', ') || 'не определены'}</p>
    {file.reference && <p>{file.reference.referenceName && `${file.reference.referenceName} · ${file.reference.referenceVersion}. `}{file.reference.reason}</p>}
    {file.panelCandidates.filter(panel => panel.id === file.detectedPanelId).map(panel => <p key={panel.id}>Отсутствуют: {panel.missing.join(', ') || 'нет'}. Дополнительные: {panel.extra.join(', ') || 'нет'}.</p>)}
  </details>)}</section>;
}
