import React, { useMemo, useState } from 'react';
import { geneticObjectKey } from '../../../../src/utils/profileImportFormat';
import ReferenceEvidence from './ReferenceEvidence';
export default function ConverterGrid({ result, options, update, disabled }) {
  const [editor, setEditor] = useState(null);
  const [mode, setMode] = useState('source');
  const [page, setPage] = useState(0);
  const problem = useMemo(() => new Set(result.issues.filter(issue => issue.hard || issue.status === 'WARNING').map(issue => issue.locus)), [result]);
  const populated = useMemo(() => new Set(result.profiles.flatMap(profile => profile.populatedLoci)), [result]);
  const loci = result.catalogLoci.filter(locus => mode === 'all' || (mode === 'source' ? result.sourceLoci.includes(locus) : mode === 'populated' ? populated.has(locus) : problem.has(locus)));
  const current = Math.min(page, Math.max(0, Math.ceil(result.profiles.length / 50) - 1));
  return <section className="converter-card"><h2>Подготовленные профили</h2><div className="converter-actions"><label>Колонки<select className="form-input" value={mode} onChange={e => setMode(e.target.value)}><option value="source">Локусы источников</option><option value="all">Весь каталог</option><option value="populated">Заполненные</option><option value="problems">С предупреждениями и ошибками</option></select></label><span>Каталог: {result.catalogLoci.length} · источники: {result.sourceLoci.length} · заполненные: {populated.size}</span></div>
    <div className="converter-scroll converter-grid-scroll" tabIndex={0} aria-label="Таблица генотипов, горизонтальная прокрутка"><table className="converter-genotypes"><thead><tr><th>Объект</th>{loci.map(locus => <th key={locus}>{locus}</th>)}</tr></thead><tbody>{result.profiles.slice(current * 50, current * 50 + 50).map(profile => <tr key={profile.objectNumber}><th scope="row">{profile.objectNumber}</th>{loci.map(locus => <td key={locus} className={problem.has(locus) ? 'converter-problem-cell' : undefined}><button className="converter-cell-button" disabled={disabled || !profile.sourceLoci.includes(locus)} title="Изменить результат" onClick={() => setEditor({ object: profile.objectNumber, locus, value: profile.strData[locus].join(',') })}>{profile.strData[locus].join(',') || '—'}</button></td>)}</tr>)}</tbody></table></div>
    <div className="converter-actions"><button className="btn btn-secondary" disabled={!current} onClick={() => setPage(current - 1)}>Назад</button><span>Страница {current + 1} из {Math.max(1, Math.ceil(result.profiles.length / 50))}</span><button className="btn btn-secondary" disabled={(current + 1) * 50 >= result.profiles.length} onClick={() => setPage(current + 1)}>Далее</button></div>
    {editor && <div className="modal-overlay"><div className="modal-content" role="dialog" aria-modal="true" aria-labelledby="converter-edit-title"><h2 id="converter-edit-title">{editor.object} · {editor.locus}</h2>{result.profiles.find(profile => profile.objectNumber === editor.object)?.audit.filter(issue => issue.locus === editor.locus && issue.reference).map(issue => <div key={issue.id}><p>Источник: {issue.sourceFile || 'Ручной результат'} · исходное: {issue.rawValue}</p><ReferenceEvidence reference={issue.reference} />{issue.hard && issue.reference.suggestedDecision && <button className="btn btn-primary" disabled={disabled} onClick={() => { update({ ...options, cells: { ...options.cells, [issue.id]: issue.reference.suggestedDecision } }); setEditor(null); }}>Принять предложение: {issue.reference.suggestedValue}</button>}</div>)}<p>Введите отдельные аллели через запятую. Одна числовая аллель диплоидного локуса требует уточнения: 12,12 или 12,?.</p><label>Результат<input autoFocus className="form-input" maxLength={500} value={editor.value} onChange={event => setEditor({ ...editor, value: event.target.value })} /></label><div className="converter-actions"><button className="btn btn-primary" disabled={disabled} onClick={() => { update({ ...options, conflicts: { ...options.conflicts, [`merge:${geneticObjectKey(editor.object)}:${editor.locus}`]: { action: 'manual', value: editor.value } } }); setEditor(null); }}>Проверить и сохранить</button><button className="btn btn-secondary" onClick={() => setEditor(null)}>Отмена</button></div></div></div>}
  </section>;
}
